### PR TITLE
New access methods for bulk read/write operations

### PR DESCRIPTION
**Pull request by fluisgirardi**
New access methods for bulk read/write operations and updated Pascal Wrapper to these new functions. 
Plus: string access functions are now in the Pascal wrapper (you warned me and I didn't understand)

### CODE REVIEW

**Comment by kyle-github** [comment]
Thanks for this!   Can you please base the PR on the `prerelease` branch?   I keep the `release` branch as the last fully tested, verified release and there are a few things (see below) that may need to be changed.  For small fixes that do not impact the core library I will sometimes accept PRs directly onto the `release` branch.

There was some discussion in issue #162 where [I proposed a different API](https://github.com/libplctag/libplctag/issues/162#issuecomment-720109046).   It ends up being effectively the same.

Before I can including this I (or you) will need to add:

- API documentation on the [API wiki](https://github.com/libplctag/libplctag/wiki/API).
- An example program showing the use.
- A fix for the version number.   I am trying to enforce SemVer so this would be 2.3.0.

I am working on code to support raw CIP commands and several other things related to tag listing as part of the new event core, so I think the example program can wait.  

I may rename the functions slightly as "block" does not really indicate what kind of data is being returned.  I think having the word "byte" or "raw bytes" in the name would make it very clear what was being returned.   Perhaps something like this?

```c
int plc_tag_set_raw_bytes(int32_t id, int offset, uint8_t *bytes, int byte_count);
int plc_tag_get_raw_bytes(int32_t id, int offset, uint8_t *bytes, int byte_count);
```
I will work on the API docs and the version number and get that into this PR first before I merge it into the release branch. 

Also, are you OK with licensing these additions under the MPL 2.0 and LGPL licenses?  The entire C library is under those licenses and I want to keep the licensing simple for users.  

Thanks again for this great contribution!

**Comment by fluisgirardi** [comment]
Of course. Give me some time to do that.  I'm with work in progress with
these changes.

Em seg, 8 de fev de 2021 22:49, Kyle Hayes <notifications@github.com>
escreveu:

**Comment by kyle-github** [comment]
I updated the [API docs for the new raw data access functions](https://github.com/libplctag/libplctag/wiki/API#handling-raw-bytes).  Please take a look and send me any corrections.

**Comment by kyle-github** [comment]
I found a way to change the base branch!  I am merging this to the prerelease branch first and then I'll fix up the names.

**Pull request merged**
