### PR TITLE
Updated pascal wrapper and converted simple.c to a pascal example.

### PR DESCRIPTION
**Pull request by fluisgirardi**

### CODE REVIEW

**Comment by kyle-github** [comment]
Sorry for the delay.  This is blocked behind a large API addition for strings.  I will get this out this weekend.

**Comment by kyle-github** [comment]
Would you consider adding to this PR?  I have added new API functions for easier string support.

**Comment by fluisgirardi** [comment]
Hi Kyle!

Yes, I consider, since I had applications using the old API. 

The best regards,

Fabio

Em sáb, 2021-01-23 às 19:32 -0800, Kyle Hayes escreveu:
Would you consider adding to this PR?  I have added new API functions for easier string support.

**Comment by kyle-github** [comment]
Another comment: @fluisgirardi We have started breaking the wrappers out into their own projects in the libplctag org.   The C# and Julia wrappers are quite active.  Would you be willing to have the Pascal wrapper as a separate project in the libplctag org?

Best,
Kyle

**Comment by kyle-github** [comment]
Finally getting a chance to merge this.  Thanks!

**Pull request merged**
