### PR TITLE
Add UDT support and raw CIP tags.

### PR DESCRIPTION
**Pull request by kyle-github**
This adds UDT support and raw CIP support for Allen-Bradley CIP-based PLCs.

- Adds the special tag "@raw" for raw CIP.  The only supported function is plc_tag_write().  Do not call plc_tag_read().
- Adds the special tag "@udt/xyz" where "xyz" is the decimal numeric ID of the UDT/struct instance.   Get this from the tag listing.
- Update list_tags.c to pull down both the tag listing and the UDT definitions.  It does a better job of showing the data types for each tag and field.
- Add the public API function plc_tag_set_size().  This sets the internal tag buffer to the passed number of bytes.

### CODE REVIEW

**Comment by timyhac** [comment]
Hey @kyle-github - super exciting!

Where is the best way to provide feedback for this?

I'm going to start developing the C# port of the list_tags program, it will include a "PlcMapper" for UdtDefinitions to help developers more easily get that info.

**Comment by kyle-github** [comment]
Here is fine.  I won't release this until there is some testing :smiley:.  Or you can open issues.   Whatever works best for you.

**Comment by timyhac** [comment]
Running the list_tags program on the `add_udt` branch I get a failure:

```
PS C:\Users\timyh\Desktop\libplctag\out\build\x64-Debug\bin_dist> .\list_tags.exe 192.168.0.10 1,0
Starting with library version 2.4.0.
2021-09-11 12:37:26.785 thread(1) tag(0) WARN receive_forward_open_response:2164 Forward Open command failed, response code: Unsupported service. (8)
2021-09-11 12:37:26.785 thread(1) tag(0) WARN receive_forward_open_response:2167 Received CIP command unsupported error from the PLC!
Unexpected UDT field name length: 0!
Usage: list_tags <PLC IP> <PLC path>
Example: list_tags 10.1.2.3 1,0
2021-09-11 12:37:28.139 thread(2) tag(0) WARN socket_write:1365 socket write error rc=-1, errno=10093
2021-09-11 12:37:28.139 thread(2) tag(0) WARN send_eip_request:1802 Error, -37, writing socket!
2021-09-11 12:37:28.140 thread(2) tag(0) WARN perform_forward_close:1920 Sending forward close failed, PLCTAG_ERR_WRITE!
```

Here is the log with the logging level [on this line](https://github.com/libplctag/libplctag/blob/add_udt/src/examples/list_tags.c#L138) turned up to `PLCTAG_DEBUG_SPEW`
[list_tags_SPEW.zip](https://github.com/libplctag/libplctag/files/7147085/list_tags_SPEW.zip).

It does look like it is retrieving info about the UDT field names and it gets to a weird field name. I'm sure my PLC program has lots of junk in it - would it be helpful to get information about the controller? Firmware, model number etc..

----

As a sanity check, I compiled and ran the `release` branch version list_tags program, and got the expected tag listing:

```
Getting controller tags.
Getting tags for program: Program:V10.
Getting tags for program: Program:V12.
Getting tags for program: Program:Main_Program.
Tag "Program:V10.HELLO" (00c4): protocol=ab-eip&gateway=192.168.0.10&path=1,0&plc=ControlLogix&elem_size=4&elem_count=1&name=Program:V10.HELLO
Tag "B_ManualPunch" (00c1): protocol=ab-eip&gateway=192.168.0.10&path=1,0&plc=ControlLogix&elem_size=1&elem_count=1&name=B_ManualPunch
Tag "Index" (00ca): protocol=ab-eip&gateway=192.168.0.10&path=1,0&plc=ControlLogix&elem_size=4&elem_count=1&name=Index
Tag "I_MandrelPressureSwitch" (01c1): protocol=ab-eip&gateway=192.168.0.10&path=1,0&plc=ControlLogix&elem_size=1&elem_count=1&name=I_MandrelPressureSwitch
Tag "UncUnderModeLoopMax" (00c4): protocol=ab-eip&gateway=192.168.0.10&path=1,0&plc=ControlLogix&elem_size=4&elem_count=1&name=UncUnderModeLoopMax
...
...
...
```

**Comment by kyle-github** [comment]
Thanks @timyhac!

The warning shown is normal if you have a PLC that will not negotiate a 4000-byte packet size.   ENBT network modules generally do not support the CIP command.  The library handles that fine.  It just fails back to the older version of the underlying command and sets up a 500-byte packet size.  I only have one PLC that will work with the larger packet size, a ControlLogix with a L81 CPU module.  Not much later you can see:

2021-09-11 12:42:05.228 thread(3) tag(0) INFO receive_forward_open_response:2202 ForwardOpen succeeded with our connection ID 291f and the PLC connection ID 1e60141 with packet size 508.

Thanks for the log.   I think I see what is happening.   It is trying to decode the structure definition for a MESSAGE tag.   This is a system-type tag and one of the fields appears to have a name of length zero.   When I look through the data that comes back, I see that several fields either have zero length names or something else weird is going on.   I do not see as many field names as there are fields/members.  I've counted a couple of times and it looks like there are 33 members in that structure and only 31 names.  That is more than I have fingers and toes, so maybe I am counting incorrectly :-)

The docs state that all system tags may not conform to the same rules as UDTs.  This is quite frustrating as system types such as STRING, COUNTER, CONTROL etc. all work fine.  I will make a tag with the type MESSAGE and see if I can read it directly.  The underlying protocol all works, the problem is in list_tags.c itself and how it is decoding the struct/UDT definitions.  I suspect that I will need to accept zero length names and accept names without any entry at all (defaulting them to zero length).  I would be worried that the offsets and types would be correct in that case.  Why AB, why?  Why is your encoding so mind numbingly bad?

BTW, your PLC is really full.  You have almost 800 tags in it!  This is a very good stress test.   I am surprised that the tag read does not time out as it takes a long time to get the entire tag list at 500 bytes per request.  The end result is over 22kB of just the tag listing data!

**Comment by kyle-github** [comment]
Weird, I created a MESSAGE tag and it does not show the same blank fields as I see in the data from your PLC.   What firmware revision do you have?   I think my L55 CPU is still at version 12 or 16 or something but I do not think I have a version of Studio 5000 that will work with that.   I have a L61.

I updated the code to try to work around null strings for the UDT name or the member name.

**Comment by timyhac** [comment]
Amazing! I know we've been talking about this for a while, but seeing it in action - its something else! This is going to be a real game-changer.

P.S. I took a look at a few of the system-defined UDT templates that had an UNNAMED fields. For the CONTROL tag it is the "FD" field which ends up being unnamed. For the Message tag, all of the UNNAMED fields don't match up with anything in RsLogix - they're all accounted for in this listing.

```
...
 UDT CONTROL (ID f81, 12 bytes, struct handle f81):
    Field 0: CTL, offset 0, type (00d3) 32-bit bit string.
    Field 1: LEN, offset 4, type (00c4) DINT: Signed 32-bit integer value.
    Field 2: POS, offset 8, type (00c4) DINT: Signed 32-bit integer value.
    Field 3: EN, offset 3:7, type (00c1) BOOL: Boolean value.
    Field 4: EU, offset 3:6, type (00c1) BOOL: Boolean value.
    Field 5: DN, offset 3:5, type (00c1) BOOL: Boolean value.
    Field 6: EM, offset 3:4, type (00c1) BOOL: Boolean value.
    Field 7: ER, offset 3:3, type (00c1) BOOL: Boolean value.
    Field 8: UL, offset 3:2, type (00c1) BOOL: Boolean value.
    Field 9: IN, offset 3:1, type (00c1) BOOL: Boolean value.
    Field 10: *UNNAMED*, offset 3:0, type (00c1) BOOL: Boolean value.
 UDT COUNTER (ID f82, 12 bytes, struct handle f82):
...
...
 UDT MESSAGE (ID fff, 240 bytes, struct handle fff):
    Field 0: FLAGS, offset 4, type (00c3) INT: Signed 16-bit integer value.
    Field 1: EW, offset 4:2, type (00c1) BOOL: Boolean value.
    Field 2: ER, offset 4:4, type (00c1) BOOL: Boolean value.
    Field 3: DN, offset 4:5, type (00c1) BOOL: Boolean value.
    Field 4: ST, offset 4:6, type (00c1) BOOL: Boolean value.
    Field 5: EN, offset 4:7, type (00c1) BOOL: Boolean value.
    Field 6: TO, offset 5:0, type (00c1) BOOL: Boolean value.
    Field 7: EN_CC, offset 5:1, type (00c1) BOOL: Boolean value.
    Field 8: ERR, offset 6, type (00c3) INT: Signed 16-bit integer value.
    Field 9: EXERR, offset 8, type (00c4) DINT: Signed 32-bit integer value.
    Field 10: *UNNAMED*, offset 12, type (00c2) SINT: Signed 8-bit integer value.
    Field 11: ERR_SRC, offset 13, type (00c2) SINT: Signed 8-bit integer value.
    Field 12: DN_LEN, offset 14, type (00c3) INT: Signed 16-bit integer value.
    Field 13: REQ_LEN, offset 16, type (00c3) INT: Signed 16-bit integer value.
    Field 14: DestinationLink, offset 18, type (00c3) INT: Signed 16-bit integer value.
    Field 15: DestinationNode, offset 20, type (00c3) INT: Signed 16-bit integer value.
    Field 16: SourceLink, offset 22, type (00c3) INT: Signed 16-bit integer value.
    Field 17: Class, offset 24, type (00c3) INT: Signed 16-bit integer value.
    Field 18: Attribute, offset 26, type (00c3) INT: Signed 16-bit integer value.
    Field 19: Instance, offset 28, type (00c4) DINT: Signed 32-bit integer value.
    Field 20: LocalIndex, offset 32, type (00c4) DINT: Signed 32-bit integer value.
    Field 21: Channel, offset 36, type (00c2) SINT: Signed 8-bit integer value.
    Field 22: Rack, offset 37, type (00c2) SINT: Signed 8-bit integer value.
    Field 23: Group, offset 38, type (00c2) SINT: Signed 8-bit integer value.
    Field 24: Slot, offset 39, type (00c2) SINT: Signed 8-bit integer value.
    Field 25: Path, offset 40, type element type UDT (0x8fce) ASCIISTRING82.
    Field 26: *UNNAMED*, offset 128, type (00c4) DINT: Signed 32-bit integer value.
    Field 27: RemoteIndex, offset 132, type (00c4) DINT: Signed 32-bit integer value.
    Field 28: RemoteElement, offset 136, type element type UDT (0x8fce) ASCIISTRING82.
    Field 29: *UNNAMED*, offset 224, type (00c4) DINT: Signed 32-bit integer value.
    Field 30: UnconnectedTimeout, offset 228, type (00c4) DINT: Signed 32-bit integer value.
    Field 31: ConnectionRate, offset 232, type (00c4) DINT: Signed 32-bit integer value.
    Field 32: TimeoutMultipli, offset 236, type (00c2) SINT: Signed 8-bit integer value.
SUCCESS!
```

**Comment by kyle-github** [comment]
I think we still have a problem.  Below is my dump of MESSAGE from a L81 ControlLogix CPU.  The total size is the same. That's good.  All the fields with names are at the same offset and have the same type.  That's good.  Most of the unnamed fields in your dump line up fine in mine (but have names).

```text
 UDT MESSAGE (ID fff, 240 bytes, struct handle fff):
    Field 0: offsettodata, offset 0, type (00c4) DINT: Signed 32-bit integer value.
    Field 1: Flags, offset 4, type (00c3) INT: Signed 16-bit integer value.
    Field 2: EW, offset 4:2, type (00c1) BOOL: Boolean value.
    Field 3: ER, offset 4:4, type (00c1) BOOL: Boolean value.
    Field 4: DN, offset 4:5, type (00c1) BOOL: Boolean value.
    Field 5: ST, offset 4:6, type (00c1) BOOL: Boolean value.
    Field 6: EN, offset 4:7, type (00c1) BOOL: Boolean value.
    Field 7: TO, offset 5:0, type (00c1) BOOL: Boolean value.
    Field 8: EN_CC, offset 5:1, type (00c1) BOOL: Boolean value.
    Field 9: ERR, offset 6, type (00c3) INT: Signed 16-bit integer value.
    Field 10: EXERR, offset 8, type (00c4) DINT: Signed 32-bit integer value.
    Field 11: exerrlength, offset 12, type (00c2) SINT: Signed 8-bit integer value.
    Field 12: ERR_SRC, offset 13, type (00c2) SINT: Signed 8-bit integer value.
    Field 13: DN_LEN, offset 14, type (00c3) INT: Signed 16-bit integer value.
    Field 14: REQ_LEN, offset 16, type (00c3) INT: Signed 16-bit integer value.
    Field 15: DestinationLink, offset 18, type (00c3) INT: Signed 16-bit integer value.
    Field 16: DestinationNode, offset 20, type (00c3) INT: Signed 16-bit integer value.
    Field 17: SourceLink, offset 22, type (00c3) INT: Signed 16-bit integer value.
    Field 18: Class, offset 24, type (00c3) INT: Signed 16-bit integer value.
    Field 19: Attribute, offset 26, type (00c3) INT: Signed 16-bit integer value.
    Field 20: Instance, offset 28, type (00c4) DINT: Signed 32-bit integer value.
    Field 21: LocalIndex, offset 32, type (00c4) DINT: Signed 32-bit integer value.
    Field 22: Channel, offset 36, type (00c2) SINT: Signed 8-bit integer value.
    Field 23: Rack, offset 37, type (00c2) SINT: Signed 8-bit integer value.
    Field 24: Group, offset 38, type (00c2) SINT: Signed 8-bit integer value.
    Field 25: Slot, offset 39, type (00c2) SINT: Signed 8-bit integer value.
    Field 26: Path, offset 40, type element type UDT (0x8fce) STRING.
    Field 27: Reserved1, offset 128, type (00c4) DINT: Signed 32-bit integer value.
    Field 28: RemoteIndex, offset 132, type (00c4) DINT: Signed 32-bit integer value.
    Field 29: RemoteElement, offset 136, type element type UDT (0x8fce) STRING.
    Field 30: Reserved2, offset 224, type (00c4) DINT: Signed 32-bit integer value.
    Field 31: UnconnectedTimeout, offset 228, type (00c4) DINT: Signed 32-bit integer value.
    Field 32: ConnectionRate, offset 232, type (00c4) DINT: Signed 32-bit integer value.
    Field 33: TimeoutMultiplier, offset 236, type (00c2) SINT: Signed 8-bit integer value.
```

The last field is "TimeoutMultiplier" not "TimeoutMultipli".  That is not good.   Can you use tag_rw2 and read tag "@udt/4095"?   With debug level 4?  I want to see if I am getting exactly the same amount of data on each PLC.  It looks like I am not and that there is something weird happening.

I had to do some odd things to make the packet request size field work right for UDTs.   Unlike other CIP commands, you do not just send the total size and an offset.   You send the offset as normal, but the total size gets decremented by the amount you are offset in the data.   WTF?  Nothing else works this way.  I wonder if the calculation is even weirder than I thought and I need to add back in a couple bytes more length.   

What version of firmware are you running?  There has to be a reason for the difference here.

**Comment by timyhac** [comment]
Yep can do - firmware is v19.11.

What should the command look like, particularly with the type argument:
`.\tag_rw2.exe --tag="protocol-ab_eip&gateway=192.168.0.10&path=1,0&cpu=ControlLogix&name=@udt/4095" --debug=4 --type=???`

**Comment by kyle-github** [comment]
Ah ha!  I checked a MESSAGE on a L61:

```text
 UDT MESSAGE (ID fff, 240 bytes, struct handle fff):
    Field 0: FLAGS, offset 4, type (00c3) INT: Signed 16-bit integer value.
    Field 1: EW, offset 4:2, type (00c1) BOOL: Boolean value.
    Field 2: ER, offset 4:4, type (00c1) BOOL: Boolean value.
    Field 3: DN, offset 4:5, type (00c1) BOOL: Boolean value.
    Field 4: ST, offset 4:6, type (00c1) BOOL: Boolean value.
    Field 5: EN, offset 4:7, type (00c1) BOOL: Boolean value.
    Field 6: TO, offset 5:0, type (00c1) BOOL: Boolean value.
    Field 7: EN_CC, offset 5:1, type (00c1) BOOL: Boolean value.
    Field 8: ERR, offset 6, type (00c3) INT: Signed 16-bit integer value.
    Field 9: EXERR, offset 8, type (00c4) DINT: Signed 32-bit integer value.
    Field 10: *UNNAMED*, offset 12, type (00c2) SINT: Signed 8-bit integer value.
    Field 11: ERR_SRC, offset 13, type (00c2) SINT: Signed 8-bit integer value.
    Field 12: DN_LEN, offset 14, type (00c3) INT: Signed 16-bit integer value.
    Field 13: REQ_LEN, offset 16, type (00c3) INT: Signed 16-bit integer value.
    Field 14: DestinationLink, offset 18, type (00c3) INT: Signed 16-bit integer value.
    Field 15: DestinationNode, offset 20, type (00c3) INT: Signed 16-bit integer value.
    Field 16: SourceLink, offset 22, type (00c3) INT: Signed 16-bit integer value.
    Field 17: Class, offset 24, type (00c3) INT: Signed 16-bit integer value.
    Field 18: Attribute, offset 26, type (00c3) INT: Signed 16-bit integer value.
    Field 19: Instance, offset 28, type (00c4) DINT: Signed 32-bit integer value.
    Field 20: LocalIndex, offset 32, type (00c4) DINT: Signed 32-bit integer value.
    Field 21: Channel, offset 36, type (00c2) SINT: Signed 8-bit integer value.
    Field 22: Rack, offset 37, type (00c2) SINT: Signed 8-bit integer value.
    Field 23: Group, offset 38, type (00c2) SINT: Signed 8-bit integer value.
    Field 24: Slot, offset 39, type (00c2) SINT: Signed 8-bit integer value.
    Field 25: Path, offset 40, type element type UDT (0x8fce) ASCIISTRING82.
    Field 26: *UNNAMED*, offset 128, type (00c4) DINT: Signed 32-bit integer value.
    Field 27: RemoteIndex, offset 132, type (00c4) DINT: Signed 32-bit integer value.
    Field 28: RemoteElement, offset 136, type element type UDT (0x8fce) ASCIISTRING82.
    Field 29: *UNNAMED*, offset 224, type (00c4) DINT: Signed 32-bit integer value.
    Field 30: UnconnectedTimeout, offset 228, type (00c4) DINT: Signed 32-bit integer value.
    Field 31: ConnectionRate, offset 232, type (00c4) DINT: Signed 32-bit integer value.
    Field 32: TimeoutMultipli, offset 236, type (00c2) SINT: Signed 8-bit integer value.
```

I get the same truncation as you.   Phwew.  If I can repro it, I can fix it.

**Comment by kyle-github** [comment]
For the tag_rw2 command, just use uint8.   That will print everything out as bytes.   Since I now have a repro case, I can focus on fixing this.

**Comment by timyhac** [comment]
Great! - for reference here is the output from my setup: [tag_rw2_output.zip](https://github.com/libplctag/libplctag/files/7148581/tag_rw2_output.zip)

**Comment by kyle-github** [comment]
OK.  One more try.   I guessed that AB would need the request to be a multiple of 4 bytes in size.  So I rounded up the request size.   That seems to work:

```text
 UDT MESSAGE (ID fff, 240 bytes, struct handle fff):
    Field 0: FLAGS, offset 4, type (00c3) INT: Signed 16-bit integer value.
    Field 1: EW, offset 4:2, type (00c1) BOOL: Boolean value.
    Field 2: ER, offset 4:4, type (00c1) BOOL: Boolean value.
    Field 3: DN, offset 4:5, type (00c1) BOOL: Boolean value.
    Field 4: ST, offset 4:6, type (00c1) BOOL: Boolean value.
    Field 5: EN, offset 4:7, type (00c1) BOOL: Boolean value.
    Field 6: TO, offset 5:0, type (00c1) BOOL: Boolean value.
    Field 7: EN_CC, offset 5:1, type (00c1) BOOL: Boolean value.
    Field 8: ERR, offset 6, type (00c3) INT: Signed 16-bit integer value.
    Field 9: EXERR, offset 8, type (00c4) DINT: Signed 32-bit integer value.
    Field 10: *UNNAMED*, offset 12, type (00c2) SINT: Signed 8-bit integer value.
    Field 11: ERR_SRC, offset 13, type (00c2) SINT: Signed 8-bit integer value.
    Field 12: DN_LEN, offset 14, type (00c3) INT: Signed 16-bit integer value.
    Field 13: REQ_LEN, offset 16, type (00c3) INT: Signed 16-bit integer value.
    Field 14: DestinationLink, offset 18, type (00c3) INT: Signed 16-bit integer value.
    Field 15: DestinationNode, offset 20, type (00c3) INT: Signed 16-bit integer value.
    Field 16: SourceLink, offset 22, type (00c3) INT: Signed 16-bit integer value.
    Field 17: Class, offset 24, type (00c3) INT: Signed 16-bit integer value.
    Field 18: Attribute, offset 26, type (00c3) INT: Signed 16-bit integer value.
    Field 19: Instance, offset 28, type (00c4) DINT: Signed 32-bit integer value.
    Field 20: LocalIndex, offset 32, type (00c4) DINT: Signed 32-bit integer value.
    Field 21: Channel, offset 36, type (00c2) SINT: Signed 8-bit integer value.
    Field 22: Rack, offset 37, type (00c2) SINT: Signed 8-bit integer value.
    Field 23: Group, offset 38, type (00c2) SINT: Signed 8-bit integer value.
    Field 24: Slot, offset 39, type (00c2) SINT: Signed 8-bit integer value.
    Field 25: Path, offset 40, type element type UDT (0x8fce) ASCIISTRING82.
    Field 26: *UNNAMED*, offset 128, type (00c4) DINT: Signed 32-bit integer value.
    Field 27: RemoteIndex, offset 132, type (00c4) DINT: Signed 32-bit integer value.
    Field 28: RemoteElement, offset 136, type element type UDT (0x8fce) ASCIISTRING82.
    Field 29: *UNNAMED*, offset 224, type (00c4) DINT: Signed 32-bit integer value.
    Field 30: UnconnectedTimeout, offset 228, type (00c4) DINT: Signed 32-bit integer value.
    Field 31: ConnectionRate, offset 232, type (00c4) DINT: Signed 32-bit integer value.
    Field 32: TimeoutMultiplier, offset 236, type (00c2) SINT: Signed 8-bit integer value.
SUCCESS!
```

Notice the last field is now "TimeoutMultiplier".   I also see that the strings are null terminated properly now.

Oddly, when I run this against my L81 CPU, I get a _much_ larger amount of data.   > 700 bytes instead of > 500 bytes.  There is a big chunk of data at the end with the newer CPU.  No idea what all that is.

I see COUNTER and CONTROL now have full member names (some were truncated before).  So do user-created strings.  The two members for strings were given as "LEN" and "DAT" instead of "LEN" and "DATA".   Now the last one is "DATA".

Give this a whirl!

**Comment by timyhac** [comment]
Yep beautiful - I get the same result, nice job!

This looks great Kyle!

I'll start looking into libplctag.NET support

**Comment by kyle-github** [comment]
Let me know how it goes!

**Comment by timyhac** [comment]
This more or less works: https://github.com/libplctag/libplctag.NET/blob/%23124-udt/src/Examples/CSharp%20DotNetCore/ListTags.cs

There are some issues with name encodings and a few other bits and pieces, but I can see that the interop with the underlying library is all good. The new `@udt` magic tags work great!

**Comment by kyle-github** [comment]
This is now merged into the prerelease branch.   Next up release 2.4.0 with UDT support!

**Pull request merged**
