### PR TITLE
platform: Fix resource and memory leaks in socket_connect_tcp

### PR DESCRIPTION
**Pull request by jubnzv**

### CODE REVIEW

**Comment by kyle-github** [comment]
HI @jubnzv, thanks for these fixes!   Can you please base them on the prerelease branch instead of release?

All changes go through the prerelease branch first so that they can be tested without impacting the release code.   

Thanks again for these fixes!

**Comment by jubnzv** [comment]
Hi @kyle-github, I changed the base branch for this PR.
Do I need to squash these commits, or it could be done by Github on merge?

**Comment by kyle-github** [comment]
I will squash the commits when I merge.   No problem there!  Thanks.

**Comment by kyle-github** [comment]
Thanks!

**Comment by kyle-github** [comment]
I will add this to the next release.  It might be a week or two (I try not to release too often), but it will be in version 2.1.11.

Thanks again for these fixes!

**Pull request merged**
