### PR TITLE
callback with user data

### PR DESCRIPTION
**Pull request by Joylei**
This PR makes it possible to pass user data to the callback function, as #212 requested.

A new api was added
- plc_tag_register_callback2

It keeps compatible with existing code.

As to the concerns about GC, it's caller's responsibility to keep callbacks and user data on the stack, and free them after usage.

Let me know if you have any questions.

### CODE REVIEW

**Comment by kyle-github** [comment]
Hi @Joylei, thanks for this contribution.  This is pretty much how I would have done it.   I want to hold on to this for a bit while I find out what is possible and what is not within Java and specifically JNA and find out from @jkoplo and @timyhac what works for C#.  API changes are set in stone once they happen so I want to make absolutely sure this is the right way to do it before I add this function.  I can always add API functions, but not change or remove them without breaking old code. 

I wonder if rather than void* as the type for the data, we'll need to use intptr_t or uintptr_t which should be the same size.   Java, for instance, stores pointers as the long data type.  But most wrappers can handle void* because it is such a common C idiom.

The key thing I am trying to determine is what happens on GCed systems.   For instance in the JVM world, the garbage collector can move objects.  So if there is no way to somehow track the changing pointer, then the C code will call the callback with an invalid pointer and possibly crash the VM.   While, to some extent, this is the responsibility of the application/wrapper, I want to make sure that there is a very clear explanation of how to do it right or have code that does it right.

Again, thanks for this contribution!

**Comment by kyle-github** [comment]
Also, probably the name should be plc_tag_set_callback_ex() to make it clear that this is an extended version of the callback system.

I would also want to add @timyhac's request of having a PLCTAG_EVENT_CREATE_COMPLETE event too and that will require more tweaking.  That said, we can just add the event type but not generate it yet.

**Comment by kyle-github** [comment]
I raised issue [#235](https://github.com/libplctag/libplctag.NET/issues/235) with the .Net team.

**Comment by Joylei** [comment]
I'm good at .Net. It's not a problem for GCed systems. 
In .Net, there are various ways to pin memory that prevent it from moving.
- Allocate unmanaged buffer with `Marshal.AllocHGlobal`
- Use `fixed` keyword
- use `GCHandle`
- use other methods of `Marshal`

I believe there must be a similar mechanism for Java.

**Comment by kyle-github** [comment]
Thanks for the response @Joylei.   I got the same response about C#/.Net from that wrapper team.   Java is going to be more of a challenge, however we can just include a reference to the original Tag object within the Callback instance so we do not need the passed reference.

What data type is preferable to .Net?   `void*` or `intptr_t`?

**Comment by Joylei** [comment]
It's common to use `void*`. Anyway, it's up to the native library.

**Comment by kyle-github** [comment]
Thanks, @Joylei!  I have moved this to the prerelease branch.   I do all PRs (mostly, in emergencies I'll commit to release) to that branch.   That is where testing is done.   It gives me a chance to catch other merge problems and test result problems.

I am going to try to get this merged this weekend.  I will do some testing and wiki additions first.

**Comment by kyle-github** [comment]
This is going to end up as version 2.5.0 because it is an API change (SemVer).

**Comment by kyle-github** [comment]
@Joylei  I have merged this into the prerelease branch.  I fixed up how callbacks are called to conform to the C standard.  You cannot "legally" cast a function pointer from a void pointer.   There are platforms where that won't work.   C, however, does let you cast a function pointer to another function pointer.  And due to the way that C marshals arguments, a caller can pass more arguments than a callee will use without danger.   

I added a few tests and fixed up a couple other things along the way (unrelated).

Please test and make sure it passes your internal tests!  If it looks good I will push this out as version 2.5.0.  The new minor version is due to the fact that this has an API change.  I still need to update the API wiki.

**Pull request merged**
